archive_extensions = [".7z", ".zip", ".rar", ".tar"]
video_extensions = [".mkv", ".mp4", ".avi"]
audio_extensions = [".mka", ".aac", ".mp3", ".ac3"]
subtitles_extensions = [".srt", ".ass", ".ssa"]
fonts_extensions = [".ttf", ".otf"]
